# Generated by Django 5.2.8 on 2026-01-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_capacity',
            field=models.FloatField(blank=True, help_text='kWh', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_cc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='km_driven',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.FloatField(default=0, help_text='km/l or km/charge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power',
            field=models.IntegerField(blank=True, help_text='bhp', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
