# Generated by Django 5.2.8 on 2026-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_vehicle_battery_capacity_vehicle_engine_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellexchange',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sell_exchange/'),
        ),
    ]
